version: '3'

services: 
  api:
    image: student-registration-api
    ports:
      - 3000:3000
    volumes:
      - ./.docker/api/uploads:/app/static/uploads/images
  mysqlsrv:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 'MySql2021!'
      MYSQL_DATABASE: 'escola'
    ports:
      - 3306:3306
    volumes:
      - ./.docker/volumes/mysql:/var/lib/mysql
      